services:
  - type: web
    name: reactor-ai
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
